config/routes.rb
Rails.application.routes.draw do
	root to:'root#top'

	devise_for :users

	resources :users do
		resource :mygroups, only: [:show, :destroy]#属しているグループもしくは招待されたグループ
		get "history" => 'users#history'#投稿したレシピ
		get "/stock" => 'users#stock'
	end
	resources :groups do
		resource :favorites, only: [:create, :destroy]
		post "/joins" => 'groups#join'#グループに参加する
		get "/search/users" => "groups#search"#招待するユーザーを検索
		post "/search/users/:search_user_id/invites" => 'groups#invite'#招待
		patch "approval" => 'mygroups#approval'#申請承認
		delete "withdrawal" => 'mygroups#withdrawal'#退会
		patch "/change/users/:user_id/status" => 'member#change'#メンバーのステータス変更
		delete "/ban/users/:user_id/ban_user" => 'member#ban'#強制退会
	end
	resources :recipes do
		resource :keeps, only: [:create, :destroy]#ストック
		resources :steps do #料理手順
			put :sort
		end
		resources :materials do#材料
			put :sort2
		end
		post "count" => 'recipes#count'#閲覧数
	end
	resources :categories, only: [:index,:show, :create, :update, :destroy, :edit]#料理のカテゴリー詳細ページの関連で使用
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :recipes, dependent: :destroy
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
	belongs_to :group
end

app/models/group.rb
class Group < ApplicationRecord
	has_many :user_groups, dependent: :destroy
	has_many :recipes, dependent: :destroy
	has_many :users, through: :user_groups, dependent: :destroy
	has_many :favorites, dependent: :destroy
	attachment :group_image

	validates :group_name, presence: true
	validates :group_name,    length: { maximum: 15 }
	validates :group_name, uniqueness: true

    def favorited_by?(user)
          favorites.where(user_id: user.id).exists?
    end

    def self.search(search) #self.でクラスメソッドとしている
	    if search # Controllerから渡されたパラメータが!= nilの場合は、titleカラムを部分一致検索
	    	Group.where(['group_name LIKE ?', "%#{search}%"])
	    else
	    	Group.all
		end
  	end
end

app/models/keep.rb
class Keep < ApplicationRecord
	belongs_to :user
	belongs_to :recipe
end

app/models/material.rb
class Material < ApplicationRecord
	belongs_to :recipe

	include RankedModel
	ranks :material_num, class_name: 'Material'
end

app/models/recipe.rb
class Recipe < ApplicationRecord
	has_many :keeps, dependent: :destroy
	has_many :steps, inverse_of: :recipe
	has_many :materials, inverse_of: :recipe

	belongs_to :user
	belongs_to :group
	belongs_to :category

	attachment :cook_image

	accepts_nested_attributes_for :steps, reject_if: :all_blank, allow_destroy: true
	accepts_nested_attributes_for :materials, reject_if: :all_blank, allow_destroy: true

	validates :title, presence: true
	validates :title,    length: { maximum: 20 }

	def kept_by?(user)
          keeps.where(user_id: user.id).exists?
    end

    def self.search(search) #self.でクラスメソッドとしている
	    if search # Controllerから渡されたパラメータが!= nilの場合は、titleカラムを部分一致検索
	      	Recipe.where(['title LIKE ?', "%#{search}%"])
	    else
	    	Recipe.all
		end
  	end
end

app/models/step.rb
class Step < ApplicationRecord
	belongs_to :recipe
	attachment :step_image

	include RankedModel
	ranks :procedure_num, class_name: 'Step'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :account, uniqueness: true
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :user_image

  has_many :user_groups, dependent: :destroy
  has_many :groups, through: :user_groups, dependent: :destroy
  has_many :recipes, dependent: :destroy
  has_many :keeps, dependent: :destroy
  has_many :favorites, dependent: :destroy
# 検索
  def self.search(search)
    if search
      User.where(['account LIKE ?', "%#{search}%"])
    else
      User.all
    end
  end
end

app/models/user_group.rb
class UserGroup < ApplicationRecord
	belongs_to :user
	belongs_to :group
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index #検索結果
    #ーーーーーーーーーーサイドバーに必要な変数ーーーーーーーーーーーーーーーーーー
    @favorite_group = Favorite.where(user_id: current_user.id)#お気に入り登録しているグループの情報
    #ーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーー
    #ViewのFormで取得したパラメータをモデルに渡す
    open_group = Group.where(restrict: false).ids
    @search_recipe = Recipe.search(params[:search])
    @recipes = @search_recipe.where(group_id: open_group).page(params[:search_recipe]).per(18)
    @search_group = Group.search(params[:search])
    @groups = @search_group.where(id: open_group).page(params[:search_group]).per(6)
  end

  def new
  	#ーーーーーーーーーーサイドバーに必要な変数ーーーーーーーーーーーーーーーーーー
    @favorite_group = Favorite.where(user_id: current_user.id)#お気に入り登録しているグループの情報
    #ーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーー
    if current_user.user_groups.where(entry: true).count == 0
      redirect_to user_path(current_user), notice: "グループを作成もしくは参加しないとレシピは投稿できないです。"
    end
    @recipe = Recipe.new
    @material = @recipe.materials.build
    @step = @recipe.steps.build
    group = UserGroup.where(entry: true, user_id: current_user.id).pluck(:group_id)
    @ingroup = Group.where(id: group)
  end

  def create
  	@recipe = Recipe.new(recipe_params)
    @recipe.user_id = current_user.id
  	if @recipe.save
  	  redirect_to recipe_path(@recipe)
    else
      redirect_back(fallback_location: "recipes#new", notice: "タイトルが正しく入力されていません")
    end
  end

  def show
  	# 本人と公開グループに投稿したものは全てユーザーに表示させる
    #ーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーー
    @recipe = Recipe.find(params[:id])
    open_group = Group.where(restrict: false).ids
    @relations = Recipe.where(group_id: open_group, category_id: @recipe.category_id).sample(6)
    #ーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーー
    @steps = @recipe.steps.rank(:procedure_num)
    @materials = @recipe.materials.rank(:material_num)
    #ーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーー
    @group = Group.find_by(id: @recipe.group_id)
    if @group.restrict == true && !UserGroup.find_by(entry: true,  group_id: @group.id, user_id: current_user.id)
      redirect_to root_path
    end
    #ーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーー
  end

  def edit
    #ーーーーーーーーーーサイドバーに必要な変数ーーーーーーーーーーーーーーーーーー
    @favorite_group = Favorite.where(user_id: current_user.id)#お気に入り登録しているグループの情報
    #ーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーー
  	# 本人のみ編集可能
  	@recipe = Recipe.find(params[:id])
    unless @recipe.user_id == current_user.id
      redirect_to root_path
    end
    group = UserGroup.where(entry: true, user_id: current_user.id).pluck(:group_id)
    @ingroup = Group.where(id: group)
  end

  def update
  	@recipe = Recipe.find(params[:id])
  	@recipe.update(recipe_params)
  	redirect_to recipe_path(@recipe)
  end

  def destroy
  	recipe = Recipe.find(params[:id])
  	recipe.destroy
  	redirect_to user_path(current_user.id), notice: "削除しました"
  end

  def count
  	recipe = Recipe.find(params[:recipe_id])
  	recipe.views += 1
  	recipe.save
  	redirect_to recipe_path(recipe)
  end

  private
	  def recipe_params
	    params.require(:recipe).permit(:views, :title, :comment, :cook_image, :count, :category_id, :group_id, materials_attributes: [:id, :material_name, :material_num, :quantity, :done, :_destroy], steps_attributes: [:id, :procedure_num, :procedure, :done, :step_image, :_destroy])
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/keeps_helper.rb
module KeepsHelper
end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/helpers/mygroups_helper.rb
module MygroupsHelper
end

app/helpers/resipes_helper.rb
module ResipesHelper
end

app/helpers/root_helper.rb
module RootHelper
end

app/helpers/steps_helper.rb
module StepsHelper
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/recipes/_form.html.erb
<div class="recipe_form">
<%= form_for @recipe do |f| %>
  <div class="field">
    <%= f.label :title, "タイトル" %>
    <br>
    <%= f.text_field :title, placeholder: "入力必須(２０文字以内)" %>
    <%= f.collection_select :category_id, Category.all, :id, :category_name %>
    <br>
    <br>
    <%= f.label :comment, "レシピへのコメント" %>
    <br>
    <%= f.text_area :comment, :size=>"30x5" %>
    <br>
    <br>
  </div>
  <div class="field">
    <%= f.label :cook_image, "完成品画像" %>
    <%= f.attachment_field :cook_image, placeholder: "料理完成画像", class: "attachment_form" %>
  </div>
  <h3>材料</h3>
  <div id="materials">
    <%= f.fields_for :materials do |material| %>
      <%= render 'material_fields', f: material %>
    <% end %>
    <div id="links">
      <%= link_to_add_association '材料を追加',f, :materials, class: "btn btn-default" %>
    </div>
  </div>
  <h3>手順</h3>
  <div id="step">
    <%= f.fields_for :steps do |step| %>
      <%= render 'step_fields', f: step %>
    <% end %>
  <div id="links">
    <%= link_to_add_association '手順を追加',f, :steps, class: "btn btn-default" %>
  </div>
  <br>
  <div id="group">
    <%= f.label :cook_image, "投稿するグループを選択" %>
    <%= f.collection_select :group_id, @ingroup, :id, :group_name %>
  </div>
  <br>
  <%= f.submit 'レシピを投稿', class: "col-xs-6 col-xs-offset-3" %>
  <br>
  <br>
<% end %>
</div>

app/views/recipes/_material_fields.html.erb
<div class="nested-fields well well-compact">
  <div class="form-group">
    <%= f.label :材料名 %>
    <%= f.text_field :material_name, placeholder:"食材名" %>
    <%= f.text_field :quantity, placeholder:"数量" %>
    <%= link_to_remove_association "材料を削除", f %>
  </div>
</div>

app/views/recipes/_step_fields.html.erb
<div class="nested-fields well well-compact form-inline">
  <div class="form-group">
    <%= f.attachment_field :step_image, placeholder: "解説用画像", class: "attachment_form" %>
    <br>
    <%= f.text_area :procedure, placeholder:"かぶの皮を剥ぎ、1/4の大きさにカットします。" %>
    <br>
    <%= link_to_remove_association "手順を削除", f %>
  </div>
</div>

app/views/recipes/edit.html.erb
<div class="container">
	<div class="row">
		<div class="sidebar">
			<%= render 'root/sidebar' %>
		</div>
		<div class="form col-xs-8">
			<h1>レシピ編集</h1>
			<%= render 'form', recipe: @recipe %>
		</div>
	</div>
</div>

app/views/recipes/index.html.erb
<div class="container">
	<div class="row">
		<div class="sidebar">
			<%= render 'root/sidebar' %>
		</div>
		<div class="contents col-xs-8">
			<div class="header row">
				<table class="table">
					<thead>
						<tr>
							<th>検索結果</th>
						</tr>
					</thead>
					<tbody>
					<% unless @groups.count == 0 %>
						<% @groups.each do |search| %>
							<tr>
								<td>
									<%= link_to group_path(search) do %>
									<div class="icon col-xs-2">
									<%= attachment_image_tag search, :group_image, fallback: "no_image.jpg", class: "group_icon" %>
									</div>
									<div class="col-xs-7" style= "text-align: center;">
										<strong><%= search.group_name %></strong>
									</div>
									<div class="col-xs-3">
										登録者数<%= search.favorites.count %>人
									</div>
									<% end %>
								</td>
							</tr>
						<% end %>
					<% end %>
					</tbody>
				</table>
				<div class="row" style= "text-align: center;">
					<%= paginate @groups, :param_name => 'search_group' %>
				</div>
				<h2>レシピ</h2>
				<% if @recipes.count == 0 %>
				ヒットしませんでした。
				<% else %>
					<% @recipes.each do |search| %>
						<td class="recipes col-xs-4">
							<%= link_to recipe_count_path(search), method: :post do %>
							<div class=" col-xs-4">
								<ul class="thumbnail">
									<li><%= attachment_image_tag search, :cook_image, fallback: "no_image.jpg", class: "index_recipe_iamges" %></li>
									<li><%= search.title %></li>
									<li><%= search.group.group_name %></li>
									<li><span class="glyphicon glyphicon-eye-open"></span>閲覧数</li>
									<li><%= search.views %>回</li>
									<li>作成日</li>
									<li><%= search.created_at.strftime('%Y年%m月%d日') %></li>
								</ul>
							</div>
							<% end %>
						</td>
					<% end %>
				<% end %>
				<div class="row" style= "text-align: center;">
					<%= paginate @recipes, :param_name => 'search_recipe' %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/recipes/new.html.erb
<div class="container">
	<div class="row">
		<div class="sidebar">
			<%= render 'root/sidebar' %>
		</div>
		<div class="form col-xs-8">
			<h1>新規レシピ作成</h1>
			<%= render 'form', recipe: @recipe %>
			<div>
			</div>
		</div>
	</div>
</div>

app/views/recipes/show.html.erb
<div class="container">
	<div class="row">
		<!-- 投稿者----------------------------------------------------------------------------- -->
		<% if user_signed_in? && @recipe.user_id == current_user.id %>
		<div class="contributor">
			<div class="info row">
				<div class="create col-xs-10">
					<h3>
						作成日：<%= @recipe.created_at.strftime('%Y年%m月%d日') %><br>
						〜投稿元〜<%= link_to group_path(@group) do %>
						<%= @recipe.group.group_name%>
						<% end %>
					</h3>
					<% if @recipe.user_id == current_user.id %>
					<div class="recipe">
						<%= link_to '編集', edit_recipe_path(@recipe), class: "btn btn-warning glyphicon glyphicon-pencil" %>
						<%= link_to '削除',recipe_path(@recipe), method: :delete, "data-confirm" => "レシピを削除しますか？", class: "btn btn-danger glyphicon glyphicon-exclamation-sign"%>
					</div>
					<% end %>
				</div>
				<div class="count col-xs-2">
					<h4><%= @recipe.views %> 回閲覧</h4>
				</div>
				<div class="none col-xs-10">
				</div>
				<div class="keep col-xs-2">
					<% if @recipe.kept_by?(current_user) %>
					  <div>
					    <%= link_to recipe_keeps_path(@recipe), method: :delete, class: "glyphicon btn btn-default glyphicon glyphicon-folder-close" do %>
					    ストック済み
					    <% end %>
					  </div>
					<% else %>
					  <div>
					    <%= link_to recipe_keeps_path(@recipe), method: :post, class: "glyphicon btn btn-warning glyphicon glyphicon-folder-open"  do %>
					    ストックに追加
					    <% end %>
					  </div>
					<% end %>
				</div><br>
			</div><br>
			<div class="title">
				<table class="table">
					<thead>
						<tr>
							<th><h1><strong><%= @recipe.title %></strong></h1></th>
						</tr>
					</thead>
					<% unless @recipe.comment == "" %>
					<tbody>
						<tr>
							<td><h2><%= @recipe.comment %></h2></td>
						</tr>
						<tr><td></td></tr>
					</tbody>
					<% end %>
				</table>
			</div>
			<div class="image col-xs-6">
				<%= attachment_image_tag @recipe, :cook_image, fallback:"no_image.jpg" %>
			</div>
			<div class="material col-xs-6">
				<table class="table table-bordered table-sortable2" data-remote="true">
					<thead>
						<tr>
							<th>材料</th>
						</tr>
					</thead>
					<tbody>
						<% @materials.each do |material| %>
						<tr class='item', data-model_name=<%= material.class.name.underscore %> data-update-url=<%= recipe_material_sort2_path(recipe_id: material.recipe.id, material_id: material.id) %> data-remote="true">
							<%= hidden_field_tag "authenticity_token", form_authenticity_token %>
							<td>
								<h1><%= material.material_name %>(<%= material.quantity %>)</h1>
							</td>
						</tr>
						<% end %>
					</tbody>
				</table>
			</div>
			<div class="step row">
				<table class="table table-sortable" data-remote="true">
					<thead>
						<tr>
							<th>手順</th>
						</tr>
					</thead>
					<tbody>
						<% @steps.each do |step| %>
						<tr class='item', data-model_name=<%= step.class.name.underscore %> data-update-url=<%= recipe_step_sort_path(recipe_id: step.recipe.id, step_id: step.id) %> data-remote="true">
							<%= hidden_field_tag "authenticity_token", form_authenticity_token %>
							<td>
								<div class="col-xs-3">
									<%= attachment_image_tag step, :step_image, class: "setep_image" %>
								</div>
								<div class="col-xs-1"></div>
								<div class="col-xs-8">
									<h1 class="procedure" style="padding: 50px 0"><%= step.procedure %></h1>
								</div>
							</td>
						</tr>
						<% end %>
						<tr>
							<td>
							</td>
						</tr>
					</tbody>
				</table>
			</div>
		</div>
		<% elsif user_signed_in? %>
		<!-- その他アカウント------------------------------------------------------------------------ -->
		<div class="public_user">
			<div class="info row">
				<div class="create col-xs-10">
					<h3>
						作成日：<%= @recipe.created_at.strftime('%Y年%m月%d日') %><br>
						〜投稿元〜<%= link_to group_path(@group) do %>
						<%= @recipe.group.group_name%>
						<% end %>
					</h3>
				</div>
				<div class="count col-xs-2">
					<h4><%= @recipe.views %> 回閲覧</h4>
				</div><br>
				<div class="none col-xs-10">
				</div>
				<div class="keep col-xs-2">
					<% if @recipe.kept_by?(current_user) %>
					  <div>
					    <%= link_to recipe_keeps_path(@recipe), method: :delete, class: "glyphicon btn btn-default glyphicon glyphicon-folder-close" do %>
					    ストック済み
					    <% end %>
					  </div>
					<% else %>
					  <div>
					    <%= link_to recipe_keeps_path(@recipe), method: :post, class: "glyphicon btn btn-warning glyphicon glyphicon-folder-open"  do %>
					    ストックに追加
					    <% end %>
					  </div>
					<% end %>
				</div><br>
			</div><br>
			<div class="title">
				<table class="table">
					<thead>
						<tr>
							<th><h1><strong><%= @recipe.title %></strong></h1></th>
						</tr>
					</thead>
					<% unless @recipe.comment == "" %>
					<tbody>
						<tr>
							<td><h2><%= @recipe.comment %></h2></td>
						</tr>
						<tr><td></td></tr>
					</tbody>
					<% end %>
				</table>
			</div>
			<div class="image col-xs-6">
				<%= attachment_image_tag @recipe, :cook_image, fallback:"no_image.jpg" %>
			</div>
			<div class="material col-xs-6">
				<table class="table">
					<thead>
						<tr>
							<th>材料</th>
						</tr>
					</thead>
					<tbody>
						<% @materials.each do |r| %>
						<tr>
							<td>
								<h1><%= r.material_name %>(<%= r.quantity %>)</h1>
							</td>
						</tr>
						<% end %>
					</tbody>
				</table>
			</div>
			<div class="step row">
					<table class="table">
						<thead>
							<tr>
								<th>手順</th>
							</tr>
						</thead>
						<tbody>
							<% @steps.each do |r| %>
							<tr>
								<td>
									<div class="col-xs-3">
										<%= attachment_image_tag r, :step_image, class: "setep_image" %>
									</div>
									<div class="col-xs-1"></div>
									<div class="col-xs-8">
										<h1 class="procedure" style="padding: 50px 0"><%= r.procedure %></h1>
									</div>
								</td>
							</tr>
							<% end %>
						</tbody>
					</table>
				</div>
			</div>
		</div>
		<% else %>
		<!-- ゲスト------------------------------------------------------------------------ -->
		<div class="gutst">
			<div class="info row">
				<div class="create col-xs-10">
					<h3>作成日：<%= @recipe.created_at.strftime('%Y年%m月%d日') %></h3>
				</div>
				<div class="title">
					<table class="table">
						<thead>
							<tr>
								<th><h1><strong><%= @recipe.title %></strong></h1></th>
							</tr>
						</thead>
						<% unless @recipe.comment == "" %>
						<tbody>
							<tr>
								<td><h2><%= @recipe.comment %></h2></td>
							</tr>
							<tr><td></td></tr>
						</tbody>
						<% end %>
					</table>
				</div>
				<div class="image col-xs-6">
					<%= attachment_image_tag @recipe, :cook_image, fallback:"no_image.jpg" %>
				</div>
				<div class="material col-xs-6">
					<table class="table">
						<thead>
							<tr>
								<th>材料</th>
							</tr>
						</thead>
						<tbody>
							<% @materials.each do |r| %>
							<tr>
								<td>
									<h1><%= r.material_name %>(<%= r.quantity %>)</h1>
								</td>
							</tr>
							<% end %>
						</tbody>
					</table>
				</div>
				<div class="step row">
					<table class="table">
						<thead>
							<tr>
								<th>手順</th>
							</tr>
						</thead>
						<tbody>
							<% @steps.each do |r| %>
							<tr>
								<td>
									<div class="col-xs-3">
										<%= attachment_image_tag r, :step_image, class: "setep_image" %>
									</div>
									<div class="col-xs-1"></div>
									<div class="col-xs-8">
										<h1 class="procedure" style="padding: 50px 0"><%= r.procedure %></h1>
									</div>
								</td>
							</tr>
							<% end %>
						</tbody>
					</table>
				</div>
			</div>
		</div>
		<% end %>
		<!-- ----------------------------------------------------------------------------- -->
		<div class="row">
			<h2>関連レシピ</h2>
			<% @relations.each do |r| %>
			<div class="relations col-xs-4">
				<ul class="thumbnail">
					<li class="recipes">
						<%= link_to recipe_count_path(r), method: :post do %>
								<li>
									<div class="relations_image">
									<%= attachment_image_tag r, :cook_image, fallback: "no_image.jpg", class: "relations_image" %>
									</div>
								</li>
								<li><%= truncate(r.title, length:10) %></li>
								<li><%= truncate(r.group.group_name, length:10) %></li>
								<li><span class="glyphicon glyphicon-eye-open"></span>閲覧数</li>
								<li><%= r.views %>回</li>
								<li>作成日</li>
								<li><%= r.created_at.strftime('%Y年%m月%d日') %></li>
						<% end %>
					</li>
				</ul>
			</div>
			<% end %>
		</div>
	</div>
</div>