config/routes.rb
Rails.application.routes.draw do
	root to:'root#top'

	devise_for :users

	resources :users do
		resource :mygroups, only: [:show, :destroy]#属しているグループもしくは招待されたグループ
		get "history" => 'users#history'#投稿したレシピ
		get "/stock" => 'users#stock'
	end
	resources :groups do
		resource :favorites, only: [:create, :destroy]
		post "/joins" => 'groups#join'#グループに参加する
		get "/search/users" => "groups#search"#招待するユーザーを検索
		post "/search/users/:search_user_id/invites" => 'groups#invite'#招待
		patch "approval" => 'mygroups#approval'#申請承認
		delete "withdrawal" => 'mygroups#withdrawal'#退会
		patch "/change/users/:user_id/status" => 'member#change'#メンバーのステータス変更
		delete "/ban/users/:user_id/ban_user" => 'member#ban'#強制退会
	end
	resources :recipes do
		resource :keeps, only: [:create, :destroy]#ストック
		resources :steps do #料理手順
			put :sort
		end
		resources :materials do#材料
			put :sort2
		end
		post "count" => 'recipes#count'#閲覧数
	end
	resources :categories, only: [:index,:show, :create, :update, :destroy, :edit]#料理のカテゴリー詳細ページの関連で使用
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :recipes, dependent: :destroy
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
	belongs_to :group
end

app/models/group.rb
class Group < ApplicationRecord
	has_many :user_groups, dependent: :destroy
	has_many :recipes, dependent: :destroy
	has_many :users, through: :user_groups, dependent: :destroy
	has_many :favorites, dependent: :destroy
	attachment :group_image

	validates :group_name, presence: true
	validates :group_name,    length: { maximum: 15 }
	validates :group_name, uniqueness: true

    def favorited_by?(user)
          favorites.where(user_id: user.id).exists?
    end

    def self.search(search) #self.でクラスメソッドとしている
	    if search # Controllerから渡されたパラメータが!= nilの場合は、titleカラムを部分一致検索
	    	Group.where(['group_name LIKE ?', "%#{search}%"])
	    else
	    	Group.all
		end
  	end
end

app/models/keep.rb
class Keep < ApplicationRecord
	belongs_to :user
	belongs_to :recipe
end

app/models/material.rb
class Material < ApplicationRecord
	belongs_to :recipe

	include RankedModel
	ranks :material_num, class_name: 'Material'
end

app/models/recipe.rb
class Recipe < ApplicationRecord
	has_many :keeps, dependent: :destroy
	has_many :steps, inverse_of: :recipe
	has_many :materials, inverse_of: :recipe

	belongs_to :user
	belongs_to :group
	belongs_to :category

	attachment :cook_image

	accepts_nested_attributes_for :steps, reject_if: :all_blank, allow_destroy: true
	accepts_nested_attributes_for :materials, reject_if: :all_blank, allow_destroy: true

	validates :title, presence: true
	validates :title,    length: { maximum: 20 }

	def kept_by?(user)
          keeps.where(user_id: user.id).exists?
    end

    def self.search(search) #self.でクラスメソッドとしている
	    if search # Controllerから渡されたパラメータが!= nilの場合は、titleカラムを部分一致検索
	      	Recipe.where(['title LIKE ?', "%#{search}%"])
	    else
	    	Recipe.all
		end
  	end
end

app/models/step.rb
class Step < ApplicationRecord
	belongs_to :recipe
	attachment :step_image

	include RankedModel
	ranks :procedure_num, class_name: 'Step'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :account, uniqueness: true
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :user_image

  has_many :user_groups, dependent: :destroy
  has_many :groups, through: :user_groups, dependent: :destroy
  has_many :recipes, dependent: :destroy
  has_many :keeps, dependent: :destroy
  has_many :favorites, dependent: :destroy
# 検索
  def self.search(search)
    if search
      User.where(['account LIKE ?', "%#{search}%"])
    else
      User.all
    end
  end
end

app/models/user_group.rb
class UserGroup < ApplicationRecord
	belongs_to :user
	belongs_to :group
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  # グループの閲覧制限・編集制限
  before_action :owner, only:[:edit, :update, :destroy]

  def owner
    unless
      @owner = UserGroup.find_by(entry: true, owner: true,  group_id:  params[:id], user_id: current_user.id)
      redirect_to root_path
    end
  end
  # ーーーーーーーーーーーーーーー
  def index
    @groups = Group.all
  end

  def new
    #ーーーーーーーーーーサイドバーに必要な変数ーーーーーーーーーーーーーーーーーー
    @favorite_group = Favorite.where(user_id: current_user.id)#お気に入り登録しているグループの情報
    #ーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーー
    @new_group = Group.new
  end
  def create
    if UserGroup.where(user_id: current_user.id, creater: true).count >= 3
      redirect_to root_path , notice: "作成できるグループは上限３つまで。"
    else
      @new_group = Group.new(group_params)
      if @new_group.save
        @user_group = UserGroup.new(user_id: current_user.id, group_id: @new_group.id, entry: true, owner: true, creater: true)
        @user_group.save
        redirect_to group_path(@new_group)
      else
        redirect_back(fallback_location: "groups#new", notice: "グループ名が正しく入力されていません")
      end
    end
  end

  def show
    #ーーーーーーーーーーサイドバーに必要な変数ーーーーーーーーーーーーーーーーーー
    @favorite_group = Favorite.where(user_id: current_user.id)#お気に入り登録しているグループの情報
    #ーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーー
    @group = Group.find(params[:id])
    @joingroups = @group.user_groups.where(entry: true).count
    @favogroups = @group.favorites.count
    @popularity = @group.recipes.order(views: "DESC").limit(6)
    @group_recipes = @group.recipes.order(created_at: "DESC").page(params[:group]).per(18)
    if @group.restrict && !UserGroup.find_by(entry: true,  group_id: @group.id, user_id: current_user.id)
      redirect_to root_path
    end
  end

  def edit
    #ーーーーーーーーーーサイドバーに必要な変数ーーーーーーーーーーーーーーーーーー
    @favorite_group = Favorite.where(user_id: current_user.id)#お気に入り登録しているグループの情報
    #ーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーー
    @group = Group.find(params[:id])
    @invite_group = UserGroup.new
  end

  def update
    @group = Group.find(params[:id])
    @group.update(group_params)
    redirect_to group_path(@group)
  end

  def destroy
    group = Group.find(params[:id])
    group.destroy
    redirect_to root_path, notice: "グループを削除しました"
  end
  # 招待
  def invite
    if UserGroup.find_by(group_id: params[:group_id], user_id: params[:search_user_id])
      flash[:notice] = "このユーザーはすでにグループに登録されています。"
    else
      @invite_group = UserGroup.new(group_id: params[:group_id], user_id: params[:search_user_id])
      @invite_group.save
    end
    redirect_to edit_group_path(params[:group_id])
  end
  # 参加
  def join
    if UserGroup.find_by(group_id: params[:group_id], user_id: current_user.id)
      flash[:notice] = "すでにグループに登録済みです。"
    else
      join_group = UserGroup.new(user_id: current_user.id, group_id: params[:group_id], entry: true)
      join_group.save
    end
    redirect_to group_path(params[:group_id])
  end

  def search
    @group = Group.find(params[:group_id])
    @user_search = User.search(params[:search])
  end
  private
    def group_params
      params.require(:group).permit(:group_name, :group_image, :lock, :restrict)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/keeps_helper.rb
module KeepsHelper
end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/helpers/mygroups_helper.rb
module MygroupsHelper
end

app/helpers/resipes_helper.rb
module ResipesHelper
end

app/helpers/root_helper.rb
module RootHelper
end

app/helpers/steps_helper.rb
module StepsHelper
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/groups/edit.html.erb
<div class="container">
	<div class="row">
		<div class="sidebar">
			<%= render 'root/sidebar' %>
		</div>
		<div class="edit_form col-xs-8">
			<%= form_for(@group) do |f| %>
				<% if @group.errors.any? %>
				    <div id="error_explanation">
				      <h2><%= @group.errors.count %>件のエラーが発生しました。</h2>
				      <ul>
				      <% @group.errors.full_messages.each do |message| %>
				        <li><%= message %></li>
				      <% end %>
				      </ul>
				    </div>
				<% end %>
			<div class="edit_form row thumbnail">
				<div class="group_set row">
					<br>
					<br>
					<div class="name_edit">
						<%= f.label :グループ名 %><br>
						<%= f.text_field :group_name %>
					</div><br>
					<div class="select">
					  <%= f.label :参加制限 %><br>
					  <%= f.select(:lock, [['全ての人が参加できる', false], ['招待した人のみ参加ができる', true]]) %>
					</div><br>
					<div class="select">
					  <%= f.label :閲覧制限 %><br>
					  <%= f.select(:restrict, [['全ての人が閲覧ができる', false], ['メンバーのみ閲覧ができる', true]]) %>
					</div><br>
				</div>
				<br>
				<br>
				<div class="image_edit">
					<%= f.label :グループ画像を選択してください %>
					<br>
					<br>
					<%= f.attachment_field :group_image, placeholder: "グループ画像", class: "attachment_form" %>
					<p>(画像を選択しなかった場合既存のものが表示されます。)</p>
				</div>
				<br>
				<div class="submit">
					<%= f.submit " 更新 " %>
				</div>
				<% end %>
			</div>
			<div class="search">
				<p>招待したい人のアカウントIDを入力してください</p>
				<%= form_tag group_search_users_path(@group), :method => 'get' do %>
					<%= text_field_tag :search %>
				<%= submit_tag "招待", :account => nil %>
				<% end %>
			</div>
			<div class="member row">
				<table class="table">
					<thead>
						<tr>
							<th>メンバー</th>
							<th>ステータス</th>
							<th></th>
							<th></th>
						</tr>
					</thead>
					<tbody>
						<% @group.user_groups.each do |g| %>
						<tr>
							<th>
								<%= g.user.name %>
							</th>
							<th>
								<% if g.owner == true %>
								<p><strong>オーナー</strong></p>
								<% elsif UserGroup.find_by(user_id: g.user.id, entry: true, owner: false) %>
								<p><strong>メンバー</strong></p>
								<% else UserGroup.find_by(user_id: g.user.id, entry: false, owner: false) %>
								<p><strong>招待中</strong></p>
								<% end %>
							</th>
							<th>
								<%if g.owner == true %>
								<%= link_to "一般に戻す",  {:action=>"change", :controller=>"member", :group_id=>@group.id, :user_id=>g.user.id}, method: :patch %>
								<% elsif UserGroup.find_by(user_id: g.user.id, entry: true, owner: false) %>
								<%= link_to "オーナーにする",  {:action=>"change", :controller=>"member", :group_id=>@group.id, :user_id=>g.user.id}, method: :patch %>
								<% else UserGroup.find_by(user_id: g.user.id, entry: false, owner: false) %>
								<%= link_to "招待取り消し",  {:action=>"ban", :controller=>"member", :group_id=>@group.id, :user_id=>g.user.id}, method: :delete %>
								<% end %>
							</th>
							<th>
								<%= link_to "グループ退会",  {:action=>"ban", :controller=>"member", :group_id=>@group.id, :user_id=>g.user.id}, method: :delete %>
							</th>
						</tr>
						<% end %>
					</tbody>
				</table>
			</div>
			<br><br><br>
			<div class="row" style= "text-align: center;">
				<%= link_to '削除',group_path(@group), method: :delete, "data-confirm" => "グループを削除しますか？", class: "btn btn-danger glyphicon glyphicon-exclamation-sign"%>
			</div>
		</div>
	</div>
</div>

app/views/groups/new.html.erb
<div class="container">
	<div class="row">
		<div class="sidebar">
			<%= render 'root/sidebar' %>
		</div>
		<div class="form col-xs-6">
		<%= form_for(@new_group) do |g| %>
			<div class="field">
			  <%= g.label :グループの名前 %><br>
			  <%= g.text_field :group_name, :size=>"25x10", placeholder:"グループの名前（15文字以内）"%>
			</div><br>
			<div class="field">
			  <%= g.label :グループの画像 %><br>
			  <%= g.attachment_field :group_image, placeholder:"グループの画像", class: "attachment_form" %>
			</div><br>
			<div class="select">
			  <%= g.label :参加権限 %><br>
			  <%= g.select(:lock, [['全ての人が参加できます', false], ['招待した人のみ', true]]) %>
			</div><br>
			<div class="select">
			  <%= g.label :閲覧制限 %><br>
			  <%= g.select(:restrict, [['全べての人が閲覧できます', false], ['メンバーのみ閲覧できます', true]]) %>
			</div><br>
			<div class="actions">
			  <p></p>
			  <%= g.submit "新規作成" %>
			</div>
		</div>
		<% end %>
	</div>
</div>

app/views/groups/search.html.erb
<div class="container">
	<div class="row">
		<div class="none col-xs-3">
		</div>
		<div class="search_users col-xs-6">
			<table class="table">
				<thead>
					<tr>
						<th>ユーザー名</th>
						<th>アカウントID</th>
						<th></th>
					</tr>
				</thead>
				<tbody>
					<% @user_search.each do |s| %>
					<tr>
						<th><%= s.name %></th>
						<th><%= s.account %></th>
						<th>
							<%= link_to "招待",  {:action=>"invite", :controller=>"groups", :group_id=>@group.id, :search_user_id=>s.id}, method: :post %>
							</th>
					</tr>
					<% end %>
				</tbody>
			</table>
		</div>
	</div>
</div>

app/views/groups/show.html.erb
<div class="container">
	<div class="row">
		<div class="sidebar">
			<%= render 'root/sidebar' %>
		</div>
		<div class="contents col-xs-8">
			<div class="header row">
				<table>
					<thead>
						<tr><th><h4>参加人数<%= @joingroups %>人/登録者数<%= @favogroups %>人</h4></th></tr>
					</thead>
					<tbody>
						<tr>
							<td>
								<div class="favarite col-xs-6">
									<% if @group.favorited_by?(current_user) %>
									  <div>
									    <%= link_to group_favorites_path(@group), method: :delete, class: "glyphicon btn btn-default" do %>
									    グループ登録済み <%= @group.favorites.count %>
									    <% end %>
									  </div>
									<% else %>
									  <div>
									    <%= link_to group_favorites_path(@group), method: :post, class: "glyphicon btn btn-danger"  do %>
									    グループ登録 <%= @group.favorites.count %>
									 	<% end %>
									  </div>
									<% end %>
								</div>
								<div class="group_join col-xs-6">
									<% if @group.lock == false && !UserGroup.find_by(entry: true,  group_id: @group.id, user_id: current_user.id)%>
									<%= link_to 'グループに参加', group_joins_path(@group), method: :post, class: 'glyphicon btn btn-success' %>
									<% end %>
								</div>
							</td>
						</tr>
					</tbody>
				</table><br>
				<div class="group_img col-xs-2">
					<%= attachment_image_tag @group, :group_image, fallback: "no_image.jpg" %>
				</div>
				<div class="group_name col-xs-10">
					<h1><%= @group.group_name %></h1>
				</div>
			</div><br>
			<div class="row">
				<% if UserGroup.find_by(group_id: @group.id, user_id: current_user.id, entry: true, owner: true) %>
				<%= link_to"", edit_group_path(@group), class: 'col-xs-12 btn btn-default glyphicon glyphicon-wrench'%>
				<% end %>
			</div><br>
			<% if @group.recipes.count > 6 %>
			<h1>人気レシピ</h1>
			<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
				<div class="carousel-inner" role="listbox">
					<div class="item active">
						<%= link_to recipe_count_path(@popularity[0]), method: :post do %>
						<div>
							<ul>
								<li><h1><strong><%= @popularity[0].title %></strong></h1></li>
								<li class="slide"><%= attachment_image_tag @popularity[0], :cook_image, fallback: "no_image.jpg", class: "slide" %></li>
							</ul>
						</div>
						<% end %>
					</div>
					<div class="item">
						<%= link_to recipe_count_path(@popularity[1]), method: :post do %>
						<div>
							<ul>
								<li><h1><strong><%= @popularity[1].title %></strong></h1></li>
								<li class="slide"><%= attachment_image_tag @popularity[1], :cook_image, fallback: "no_image.jpg", class: "slide" %></li>
							</ul>
						</div>
						<% end %>
					</div>
					<div class="item">
						<%= link_to recipe_count_path(@popularity[2]), method: :post do %>
						<div>
							<ul>
								<li><h1><strong><%= @popularity[2].title %></strong></h1></li>
								<li class="slide"><%= attachment_image_tag @popularity[2], :cook_image, fallback: "no_image.jpg", class: "slide" %></li>
							</ul>
						</div>
						<% end %>
					</div>
					<div class="item">
						<%= link_to recipe_count_path(@popularity[3]), method: :post do %>
						<div>
							<ul>
								<li><h1><strong><%= @popularity[3].title %></strong></h1></li>
								<li class="slide"><%= attachment_image_tag @popularity[3], :cook_image, fallback: "no_image.jpg", class: "slide" %></li>
							</ul>
						</div>
						<% end %>
					</div>
					<div class="item">
						<%= link_to recipe_count_path(@popularity[4]), method: :post do %>
						<div>
							<ul>
								<li><h1><strong><%= @popularity[4].title %></strong></h1></li>
								<li class="slide"><%= attachment_image_tag @popularity[4], :cook_image, fallback: "no_image.jpg", class: "slide" %></li>
							</ul>
						</div>
						<% end %>
					</div>
					<div class="item">
						<%= link_to recipe_count_path(@popularity[5]), method: :post do %>
						<div>
							<ul>
								<li><h1><strong><%= @popularity[5].title %></strong></h1></li>
								<li class="slide"><%= attachment_image_tag @popularity[5], :cook_image, fallback: "no_image.jpg", class: "slide" %></li>
							</ul>
						</div>
						<% end %>
					</div>
				</div>
				<a class="left carousel-control" href="#carouselExampleControls" role="button" data-slide="prev">
					<span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
					<span class="sr-only">前へ</span>
				</a>
				<a class="right carousel-control" href="#carouselExampleControls" role="button" data-slide="next">
					<span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
					<span class="sr-only">次へ</span>
				</a>
			</div><br>
			<% end %>
			<div class="row">
				<table class="table table-hover">
					<thead>
						<tr>
							<th></th>
							<th>グループレシピ</th>
							<th></th>
						</tr>
					</thead>
					<tbody>
						<% @group_recipes.each do |h| %>
						<tr class="row">
							<td class="recipes">
								<%= link_to recipe_path(h) do %>
								<div class="col-xs-4">
									<%= attachment_image_tag h, :cook_image, fallback: "no_image.jpg", class: "index_recipe_iamges" %>
								</div>
								<div class="info col-xs-8">
									<ul>
										<li><h4><strong><%= h.title %></strong></h4></li>
										<br>
										<li><%= h.group.group_name %>・<span class="glyphicon glyphicon-eye-open">閲覧数：</span><%= h.views %>回</li>
										<li>作成日<%= h.created_at.strftime('%Y年%m月%d日') %></li>
									</ul>
								</div>
								<% end %>
							</td>
						</tr>
						<% end %>
					</tbody>
				</table>
			</div>
			<div class="row" style= "text-align: center;">
				<%= paginate @group_recipes, :param_name => 'group' %>
			</div>
		</div>
	</div>
</div>