config/routes.rb
Rails.application.routes.draw do
	root to:'root#top'

	devise_for :users

	resources :users do
		resource :mygroups, only: [:show, :destroy]#属しているグループもしくは招待されたグループ
		get "history" => 'users#history'#投稿したレシピ
		get "/stock" => 'users#stock'
	end
	resources :groups do
		resource :favorites, only: [:create, :destroy]
		post "/joins" => 'groups#join'#グループに参加する
		get "/search/users" => "groups#search"#招待するユーザーを検索
		post "/search/users/:search_user_id/invites" => 'groups#invite'#招待
		patch "approval" => 'mygroups#approval'#申請承認
		delete "withdrawal" => 'mygroups#withdrawal'#退会
		patch "/change/users/:user_id/status" => 'member#change'#メンバーのステータス変更
		delete "/ban/users/:user_id/ban_user" => 'member#ban'#強制退会
	end
	resources :recipes do
		resource :keeps, only: [:create, :destroy]#ストック
		resources :steps do #料理手順
			put :sort
		end
		resources :materials do#材料
			put :sort2
		end
		post "count" => 'recipes#count'#閲覧数
	end
	resources :categories, only: [:index,:show, :create, :update, :destroy, :edit]#料理のカテゴリー詳細ページの関連で使用
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :recipes, dependent: :destroy
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
	belongs_to :group
end

app/models/group.rb
class Group < ApplicationRecord
	has_many :user_groups, dependent: :destroy
	has_many :recipes, dependent: :destroy
	has_many :users, through: :user_groups, dependent: :destroy
	has_many :favorites, dependent: :destroy
	attachment :group_image

	validates :group_name, presence: true
	validates :group_name,    length: { maximum: 15 }
	validates :group_name, uniqueness: true

    def favorited_by?(user)
          favorites.where(user_id: user.id).exists?
    end

    def self.search(search) #self.でクラスメソッドとしている
	    if search # Controllerから渡されたパラメータが!= nilの場合は、titleカラムを部分一致検索
	    	Group.where(['group_name LIKE ?', "%#{search}%"])
	    else
	    	Group.all
		end
  	end
end

app/models/keep.rb
class Keep < ApplicationRecord
	belongs_to :user
	belongs_to :recipe
end

app/models/material.rb
class Material < ApplicationRecord
	belongs_to :recipe

	include RankedModel
	ranks :material_num, class_name: 'Material'
end

app/models/recipe.rb
class Recipe < ApplicationRecord
	has_many :keeps, dependent: :destroy
	has_many :steps, inverse_of: :recipe
	has_many :materials, inverse_of: :recipe

	belongs_to :user
	belongs_to :group
	belongs_to :category

	attachment :cook_image

	accepts_nested_attributes_for :steps, reject_if: :all_blank, allow_destroy: true
	accepts_nested_attributes_for :materials, reject_if: :all_blank, allow_destroy: true

	validates :title, presence: true
	validates :title,    length: { maximum: 20 }

	def kept_by?(user)
          keeps.where(user_id: user.id).exists?
    end

    def self.search(search) #self.でクラスメソッドとしている
	    if search # Controllerから渡されたパラメータが!= nilの場合は、titleカラムを部分一致検索
	      	Recipe.where(['title LIKE ?', "%#{search}%"])
	    else
	    	Recipe.all
		end
  	end
end

app/models/step.rb
class Step < ApplicationRecord
	belongs_to :recipe
	attachment :step_image

	include RankedModel
	ranks :procedure_num, class_name: 'Step'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :account, uniqueness: true
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :user_image

  has_many :user_groups, dependent: :destroy
  has_many :groups, through: :user_groups, dependent: :destroy
  has_many :recipes, dependent: :destroy
  has_many :keeps, dependent: :destroy
  has_many :favorites, dependent: :destroy
# 検索
  def self.search(search)
    if search
      User.where(['account LIKE ?', "%#{search}%"])
    else
      User.all
    end
  end
end

app/models/user_group.rb
class UserGroup < ApplicationRecord
	belongs_to :user
	belongs_to :group
end

app/controllers/root_controller.rb
class RootController < ApplicationController
  PER = 12
  def top
  	#ーーーーーーーーーーサイドバーに必要な変数ーーーーーーーーーーーーーーーーーー
  	if user_signed_in?
  	@favorite_group = Favorite.where(user_id: current_user.id)#お気に入り登録しているグループの情報
  	@join_group = UserGroup.where(user_id: current_user.id, entry: true)#参加中のグループ
    #--------------------------------------------------------------
    #招待件数
    @notification = UserGroup.where(user_id: current_user.id, entry: false).count
    end
    #公開している全てのレシピ
  	#ーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーー
  	open_group = Group.where(restrict: false).ids
    @open_recipe = Recipe.where(group_id: open_group)
    #週間・月間のレシピ
    #ーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーー
    now  = Time.new.tomorrow.at_beginning_of_day
    month = (now - 1.month)
    week = (now - 7.day)
    @week_views = Recipe.where(group_id: open_group, created_at: week...now).order(views: "DESC").page(params[:week_peage]).per(PER)
  	@month_views = Recipe.where(group_id: open_group, created_at: month...now).order(views: "DESC").page(params[:month_page]).per(PER)
    #ーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーー
    @recommended = Recipe.where(group_id: open_group, created_at: month...now).sample(6)
    # @recommended = @open_recipe.find(Keep.group(:recipe_id).order('count(recipe_id) desc').limit(12).pluck(:recipe_id))
    #ーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーー
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/keeps_helper.rb
module KeepsHelper
end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/helpers/mygroups_helper.rb
module MygroupsHelper
end

app/helpers/resipes_helper.rb
module ResipesHelper
end

app/helpers/root_helper.rb
module RootHelper
end

app/helpers/steps_helper.rb
module StepsHelper
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/root/_sidebar.html.erb
<% if user_signed_in? %>
<div class="col-xs-4 hidden-xs">
	<table class="table table-hover scrool">
		<thead class="sidebar_head">
			<tr>
				<th><%=link_to "レシピ新規追加", new_recipe_path %></th>
			</tr>
			<tr>
				<th><%= link_to "グループ作成", new_group_path %></th>
			</tr>
			<tr>
				<th><%= link_to "登録グループ", user_path(current_user) %></th>
			</tr>
		</thead>
		<tbody>
			<% @favorite_group.each do |join| %>
			<tr>
				<td class="favorite_group">
					<%= link_to group_path(join.group.id) do %>
					<div class="icon col-xs-2">
					<%= attachment_image_tag join.group, :group_image, fallback: "no_image.jpg", class: "group_icon" %>
					</div>
					<div class="group_name col-xs-10">
						<strong><%= truncate(join.group.group_name, length:9) %></strong>
					</div>
					<% end %>
				</td>
			</tr>
			<% end %>
		</tbody>
	</table>
</div>
<% else %>
<% end %>

app/views/root/top.html.erb
<div class="container">
	<div class="row">
		<div class="contents">
			<!-- -------------------------------------------------------------------- -->
			<div class="row">
				<table class="table">
					<thead>
						<tr>
							<th>おすすめ</th>
						</tr>
					</thead>
				</table>
				<% @recommended.each do |v| %>
					<td class="recipes">
						<%= link_to recipe_count_path(v), method: :post do %>
						<div class="col-lg-4 col-sm-6">
							<ul class="thumbnail">
								<li><%= attachment_image_tag v, :cook_image, fallback: "no_image.jpg", class: "index_recipe_iamges" %></li>
								<li><strong><%= v.title %></strong></li><br>
								<li><%= v.group.group_name %></li>
								<li><span class="glyphicon glyphicon-eye-open"></span>閲覧数</li>
								<li><%= v.views %>回</li>
								<li>〜作成日〜</li>
								<li><%= v.created_at.strftime('%Y年%m月%d日') %></li>
							</ul>
						</div>
						<% end %>
					</td>
				<% end %>
			</div>
			<div class="row none">
			</div>
			<!-- -------------------------------------------------------------------- -->
			<% unless @week_views.count == 0 %>
			<div class="row">
				<table class="table">
					<thead>
						<tr>
							<th>週間閲覧数ランキング</th>
						</tr>
					</thead>
				</table>
				<% @week_views.each do |v| %>
					<td class="recipes">
						<%= link_to recipe_count_path(v), method: :post do %>
						<div class="col-lg-4 col-sm-6">
							<ul class="thumbnail">
								<li><%= attachment_image_tag v, :cook_image, fallback: "no_image.jpg", class: "index_recipe_iamges" %></li>
								<li><strong><%= v.title %></strong></li><br>
								<li><%= v.group.group_name %></li>
								<li><span class="glyphicon glyphicon-eye-open"></span>閲覧数</li>
								<li><%= v.views %>回</li>
								<li>〜作成日〜</li>
								<li><%= v.created_at.strftime('%Y年%m月%d日') %></li>
							</ul>
						</div>
						<% end %>
					</td>
				<% end %>
			</div>
			<div class="row" style= "text-align: center;">
				<%= paginate @week_views, :param_name => 'week_peage' %>
			</div>
			<% end %>
			<!-- -------------------------------------------------------------------- -->
			<div class="row">
				<table class="table">
					<thead>
						<tr>
							<th>月間閲覧数ランキング</th>
						</tr>
					</thead>
				</table>
				<% @month_views.each do |v| %>
					<td class="recipes">
						<%= link_to recipe_count_path(v), method: :post do %>
						<div class=" col-lg-4 col-sm-6">
							<ul class="thumbnail">
								<li><%= attachment_image_tag v, :cook_image, fallback: "no_image.jpg", class: "index_recipe_iamges" %></li>
								<li><strong><%= v.title %></strong></li><br>
								<li><%= v.group.group_name %></li>
								<li><span class="glyphicon glyphicon-eye-open"></span>閲覧数：<%= v.views %>回</li>
								<li>〜作成日〜</li>
								<li><%= v.created_at.strftime('%Y年%m月%d日') %></li>
							</ul>
						</div>
						<% end %>
					</td>
				<% end %>
			</div>
			<div class="row" style= "text-align: center;">
				<%= paginate @month_views, :param_name => 'month_page' %>
			</div>
			<!-- -------------------------------------------------------------------- -->
		</div>
	</div>
</div>