config/routes.rb
Rails.application.routes.draw do
	root to:'root#top'

	devise_for :users

	resources :users do
		resource :mygroups, only: [:show, :destroy]#属しているグループもしくは招待されたグループ
		get "history" => 'users#history'#投稿したレシピ
		get "/stock" => 'users#stock'
	end
	resources :groups do
		resource :favorites, only: [:create, :destroy]
		post "/joins" => 'groups#join'#グループに参加する
		get "/search/users" => "groups#search"#招待するユーザーを検索
		post "/search/users/:search_user_id/invites" => 'groups#invite'#招待
		patch "approval" => 'mygroups#approval'#申請承認
		delete "withdrawal" => 'mygroups#withdrawal'#退会
		patch "/change/users/:user_id/status" => 'member#change'#メンバーのステータス変更
		delete "/ban/users/:user_id/ban_user" => 'member#ban'#強制退会
	end
	resources :recipes do
		resource :keeps, only: [:create, :destroy]#ストック
		resources :steps do #料理手順
			put :sort
		end
		resources :materials do#材料
			put :sort2
		end
		post "count" => 'recipes#count'#閲覧数
	end
	resources :categories, only: [:index,:show, :create, :update, :destroy, :edit]#料理のカテゴリー詳細ページの関連で使用
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :recipes, dependent: :destroy
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
	belongs_to :group
end

app/models/group.rb
class Group < ApplicationRecord
	has_many :user_groups, dependent: :destroy
	has_many :recipes, dependent: :destroy
	has_many :users, through: :user_groups, dependent: :destroy
	has_many :favorites, dependent: :destroy
	attachment :group_image

	validates :group_name, presence: true
	validates :group_name,    length: { maximum: 15 }
	validates :group_name, uniqueness: true

    def favorited_by?(user)
          favorites.where(user_id: user.id).exists?
    end

    def self.search(search) #self.でクラスメソッドとしている
	    if search # Controllerから渡されたパラメータが!= nilの場合は、titleカラムを部分一致検索
	    	Group.where(['group_name LIKE ?', "%#{search}%"])
	    else
	    	Group.all
		end
  	end
end

app/models/keep.rb
class Keep < ApplicationRecord
	belongs_to :user
	belongs_to :recipe
end

app/models/material.rb
class Material < ApplicationRecord
	belongs_to :recipe

	include RankedModel
	ranks :material_num, class_name: 'Material'
end

app/models/recipe.rb
class Recipe < ApplicationRecord
	has_many :keeps, dependent: :destroy
	has_many :steps, inverse_of: :recipe
	has_many :materials, inverse_of: :recipe

	belongs_to :user
	belongs_to :group
	belongs_to :category

	attachment :cook_image

	accepts_nested_attributes_for :steps, reject_if: :all_blank, allow_destroy: true
	accepts_nested_attributes_for :materials, reject_if: :all_blank, allow_destroy: true

	validates :title, presence: true
	validates :title,    length: { maximum: 20 }

	def kept_by?(user)
          keeps.where(user_id: user.id).exists?
    end

    def self.search(search) #self.でクラスメソッドとしている
	    if search # Controllerから渡されたパラメータが!= nilの場合は、titleカラムを部分一致検索
	      	Recipe.where(['title LIKE ?', "%#{search}%"])
	    else
	    	Recipe.all
		end
  	end
end

app/models/step.rb
class Step < ApplicationRecord
	belongs_to :recipe
	attachment :step_image

	include RankedModel
	ranks :procedure_num, class_name: 'Step'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :account, uniqueness: true
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :user_image

  has_many :user_groups, dependent: :destroy
  has_many :groups, through: :user_groups, dependent: :destroy
  has_many :recipes, dependent: :destroy
  has_many :keeps, dependent: :destroy
  has_many :favorites, dependent: :destroy
# 検索
  def self.search(search)
    if search
      User.where(['account LIKE ?', "%#{search}%"])
    else
      User.all
    end
  end
end

app/models/user_group.rb
class UserGroup < ApplicationRecord
	belongs_to :user
	belongs_to :group
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/keeps_helper.rb
module KeepsHelper
end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/helpers/mygroups_helper.rb
module MygroupsHelper
end

app/helpers/resipes_helper.rb
module ResipesHelper
end

app/helpers/root_helper.rb
module RootHelper
end

app/helpers/steps_helper.rb
module StepsHelper
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cbook</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.3/jquery.js'></script>

    <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.0/jquery-ui.css' />
    <script src='https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.0/jquery-ui.min.js'></script>

    <script src='https://cdnjs.cloudflare.com/ajax/libs/jqueryui-touch-punch/0.2.3/jquery.ui.touch-punch.min.js'></script>
  </head>

  <body>
    <header class="navbar navbar-top">
      <div class="container">
        <div class="row">
          <nav class="nav navbar-nav navbar-left">
            <%= link_to root_path, class: "header_logo" do %>
             <%= image_tag("/images/logo.jpg", :size => "250x100", :alt => "logo") %>
            <% end %>
          </nav>
          <nav class="header_nav nav-list row">
            <ul class="nav navbar-nav navbar-right" style="color: black;">
              <% if user_signed_in? %>
              <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-expanded="false">
                  <%= image_tag("/images/header_icon.png", :size => "50x50", :alt => "header_icon") %>
                  <span class="caret"></span></a>
                <ul class="dropdown-menu" role="menu">
                  <li><strong><h2><%= current_user.name %>さん</strong></h2></li>
                  <li role="presentation">
                    <%=link_to user_path(current_user) do %>
                    <h2>登録グループ</h2>
                    <% end %>
                  </li>
                  <li role="presentation">
                    <%=link_to user_mygroups_path(current_user.id) do %>
                    <h2>Myグループ(<%= UserGroup.where(user_id: current_user.id, entry: false).count %>)</h2>
                    <% end %>
                  </li>
                  <li role="presentation">
                    <%=link_to user_stock_path(current_user.id) do %>
                    <h2>ストック</h2>
                    <% end %>
                  </li>
                  <li role="presentation">
                    <%=link_to user_history_path(current_user.id) do %>
                    <h2>投稿履歴</h2>
                    <% end %>
                  </li>
                  <li role="presentation">
                    <%= link_to edit_user_path(current_user) do %>
                    <h2>設定</h2>
                    <% end %>
                  </li>
                  <li role="presentation">
                    <%=link_to destroy_user_session_path, method: :delete do %>
                    <h2>ログアウト</h2>
                    <% end %>
                  </li>
                </ul>
              </li>
              <% else %>
                <li>
                  <%= link_to"新規登録", new_user_registration_path %>
                </li>
                <li>
                  <%= link_to"ログイン", new_user_session_path %>
                </li>
              <% end %>
            </ul>
          </nav>
        </div>
        <div class=flash-message>
        <% if flash[:notice] %>
              <p><%= flash[:notice] %></p>
            <% end %>
          </div>
      </div>
    </header>
    <div class="container-fluid">
      <div class="row">
        <div class="col-xs-1">
          <div class="left_image">
          </div>
        </div>
        <div class="col-xs-10">
          <div class="main_image">
            <main>
                <%= yield %>
            </main>
          </div>
        </div>
        <div class="col-xs-1">
          <div class="right_image">
          </div>
        </div>
      </div>
    </div>
    <footer>
      <div class="under_image">
      </div>
    </footer>
  </body>
</html>